name: jme-cdct-seg-consumer-example
services:
  pact-broker-db:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_USER: pactbroker
      POSTGRES_PASSWORD: pactbroker
      POSTGRES_DB: pactbroker
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pactbroker"]
      interval: 10s
      timeout: 5s
      retries: 12
    labels:
      org.springframework.boot.ignore: true

  pact-broker:
    image: pactfoundation/pact-broker:2.136.0-pactbroker2.117.1
    ports:
      - "9292:9292"
    depends_on:
      pact-broker-db:
        condition: service_healthy
    environment:
      PACT_BROKER_DATABASE_USERNAME: pactbroker
      PACT_BROKER_DATABASE_PASSWORD: pactbroker
      PACT_BROKER_DATABASE_HOST: pact-broker-db
      PACT_BROKER_DATABASE_NAME: pactbroker
      PACT_BROKER_BASE_URL: http://localhost:9292
      PACT_BROKER_ALLOW_PUBLIC_READ: 'true'
      PACT_BROKER_DISABLE_SSL_VERIFICATION: 'true'
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://pact-broker:9292/diagnostic/status/heartbeat" ]
      interval: 10s
      timeout: 5s
      retries: 18
